export default new Map([
  ['id', 'ID'],
  ['procedureName', 'Procedure Name'],
  ['shutDown', 'Shut down?'],
  ['workType', 'Work Type'],
  ['activityType', 'Activity Type'],
  ['wrenchTime', 'Wrench Time (hr)'],
  ['action', 'Recommended Action'],
  ['tradeType', 'Trade Type'],
  ['tradeQuantity', 'Quantity of Trade'],
  ['utilization', 'Wrench Time Utilization (%)'],
  ['description', 'Description'],
  ['name', 'Name'],
  ['parent', 'Parent'],
]);
