name: CI

on: 
  issues:
    types: [opened, edited, labeled]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SendGrid
      uses: peter-evans/sendgrid-action@v1.0.0
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SCRIPT_FILEPATH: ./.github/sendgrid.js  
