name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - name: Checkout
    #   uses: actions/checkout@master
    - name: SendGrid
      uses: peter-evans/sendgrid-action@v1.0.0
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
