name: Node CI

on: 
  push:
    branches: 
      - 'master'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create .env file
      run: |
        touch .env
        printf "VUE_APP_API=${{secrets.VUE_APP_API}}\n" >> .env
        printf "VUE_APP_URL=${{secrets.VUE_APP_URL}}\n" >> .env
        cat .env
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
        zip -r release.zip ./dist
      env:
        CI: true
    
    - name: set environment
      run: |
        echo ::set-env name=RELEASE_TAG::$(date '+%Y.%m.%d-%H.%M.%S')
        echo $RELEASE_TAG
      
    - name: Create & Upload Release
      uses: meeDamian/github-release@1.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        files: ./release.zip
    - name: Timeout for release to process
      uses: jakejarvis/wait-action@master
      with:
        time: '20s'
    - name: Update Server
      uses: wei/curl@v1
      with:
        args: https://django.tw-webapp-next.duckdns.org/djangoAPI/update-app
